# Generated by Django 4.1 on 2022-10-15 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gallery_name", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        default="media/default.jpeg", upload_to="gallery_pics/"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="gallery_name", max_length=200, unique=True
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={"ordering": ["gallery_name"],},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
                (
                    "image",
                    models.ImageField(
                        default="media/default.jpeg", upload_to="events/"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("events", "events"), ("news", "news")],
                        default="news",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="more info here", max_length=300
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={"ordering": ["-date_created"],},
        ),
    ]
